### ISSUE TITLE
train_autoencoder demo preprocess issue with tf2

### ISSUE THREAD

**Issue by Forevian** [magenta/ddsp#13]
```
Traceback (most recent call last):
  File "/usr/local/bin/ddsp_prepare_tfrecord", line 8, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.6/dist-packages/ddsp/training/data_preparation/prepare_tfrecord.py", line 91, in console_entry_point
    tf.disable_v2_behavior()
AttributeError: module 'tensorflow_core.compat.v2' has no attribute 'disable_v2_behavior'
```

**Comment by cifkao** [comment]
Changing this line https://github.com/magenta/ddsp/blob/df08b4361d69e92a9b3bac3aafdc3cd12b2b9602/ddsp/training/data_preparation/prepare_tfrecord.py#L91
to
```python
  tf.compat.v1.disable_v2_behavior()
```
seems to fix the problem.

**Comment by adarob** [comment]
Thans Ondrej. Do you want to submit a PR to fix?
