### ISSUE TITLE
Error while trying to run training

### ISSUE THREAD

**Issue by Taikakim** [magenta/ddsp#480]
Things went fine until training, the example slice loaded was fine, but I'm not sure what's wrong here now. The audio is a bit less than 10 minutes 44.1Khz mono.
 
```
# Parameters for train:
# ==============================================================================
train.batch_size = %batch_size
train.data_provider = @data.TFRecordProvider()
train.num_steps = 30000
train.steps_per_save = 300
train.steps_per_summary = 300

# Parameters for Trainer:
# ==============================================================================
Trainer.checkpoints_to_keep = 10
Trainer.grad_clip_norm = 3.0
Trainer.learning_rate = %learning_rate
Trainer.lr_decay_rate = 0.98
Trainer.lr_decay_steps = 10000

I0122 11:20:21.558923 140413582122048 train_util.py:78] Defaulting to MirroredStrategy
2023-01-22 11:20:22.384612: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0122 11:20:22.390519 140413582122048 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
Traceback (most recent call last):
  File "/usr/local/bin/ddsp_run", line 8, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.8/dist-packages/ddsp/training/ddsp_run.py", line 229, in console_entry_point
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.8/dist-packages/ddsp/training/ddsp_run.py", line 199, in main
    train_util.train(data_provider=gin.REQUIRED,
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 1545, in gin_wrapper
    new_kwargs = copy.deepcopy(new_kwargs)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 778, in __deepcopy__
    return self._scoped_configurable_fn()
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.8/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 516, in meta_call_wrapper
    return cls_meta.__call__(new_cls, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ddsp/training/data.py", line 235, in __init__
    super().__init__(file_pattern, example_secs, sample_rate,
  File "/usr/local/lib/python3.8/dist-packages/ddsp/training/data.py", line 177, in __init__
    self._file_pattern = file_pattern or self.default_file_pattern
  File "/usr/local/lib/python3.8/dist-packages/ddsp/training/data.py", line 186, in default_file_pattern
    raise NotImplementedError(
NotImplementedError: You must pass a "file_pattern" argument to the constructor or choose a FileDataProvider with a default_file_pattern.
  In call to configurable 'TFRecordProvider' (<class 'ddsp.training.data.TFRecordProvider'>)

```

**Comment by jesseengel** [comment]
Sorry for the delay, I believe you'll need to add `train.file_pattern` to either the gin file or as a `--gin_param` that points to the data you want to train on.

**Comment by Taikakim** [comment]
Thanks, I'll take a look at this again when I have a bit of time.
